- .gitignore
- LICENSE.md
- README.md
- examples/profile/certificatehelper.go
- examples/profile/main.go
- Added self-signed certificate to example project
- Cert and private key files are generated if not present (and ignored in source control)
- Redirection from HTTP->HTTPS
> SDK-376: Self-signed certificate

- examples/profile/main.go
Remove HTTPS redirection as it was causing permissions issues on Linux
> SDK-687 HTTPS redirection

- README.md
- yoti_test.go
- yoticlient.go
> SDK-804: Structured Postal Address

- README.md
- activitydetails.go
- dataobjects.go
- yoti_test.go
- yoticlient.go
- Tested two applications under the same org returning same ParentRememberMeID
> SDK-712: Parent Remember Me ID 

- attribute/genericattribute.go
- attribute/imagesliceattribute.go
- attribute/multivalueattribute.go
- attribute/parser.go
- yoti_test.go
- when there's an error parsing any of the multi value contents, don't return the partial attribute
> SDK-756: Add further tests for Multi Value parsing

- README.md
- yoticlient.go
- No plans to release this on its own, it will just be ready for when we do the next release
> SdK-719 Header

- .travis.yml
- CONTRIBUTING.md
- README.md
- attribute/parser.go
- endpoint.go
- sonar-project.properties
- yoticlient.go
Release 2.5.0
Proposed Release notes:
- SDK Identifier header
- UNDEFINED content type handling
> development -> master v2.5.0

- .travis.yml
- README.md
- examples/go.mod
- examples/go.sum
- yotiprofile.go
- Example module can be updated after v2.5.0 of the SDK was pushed live.
- Updated attribute text
> SDK-994: Update Attribute text

- examples/profile/error.html
- examples/profile/main.go
Contains changes from SDK-502 NewDemoDesign, merge that first.
>  SDK-1067: Add simple Error page 

- .gitattributes
- examples/profile/login.html
- examples/profile/main.go
- Add `clientSdkId` to Modal QR configuration
- added ` .gitattributes` to match other SDKs
> SDK-1038: Add `clientSdkId` to Modal QR config.

- attribute/documentdetailsattribute.go
- attribute/documentdetailsattribute_test.go
* Add Value(), Sources(), Verifiers() and Anchors() to DocumentDetailsAttribute to allow the DocumentDetails struct within to be accessed.
> SDK-820 missing features

- .travis.yml
* Job in travis to run coverage report and upload to coveralls.io
* Travis jobs have been split into separate jobs to support coverage report to coveralls.io
> SDK-1240: Update travis file to include coveralls support

- age_verifications.go
- requests/signed_message_test.go
- yoti_test.go
- yotiprofile.go
- yotiprofile_test.go
* Add `AgeVerification` object
* Add `AgeVerifications()` method to Profile
> SDK-574: Add AgeVerifications list to Profile

- attribute/definition.go
- extension/third_party_attribute_extension.go
- extension/third_party_attribute_extension_test.go
* `extension/ThirdPartyAttributeExtensionBuilder`
* `extension/ThirdPartyAttributeExtension`
> SDK-1261: Third Party Attribute Extension

- .travis.yml
- attribute/image_slice_attribute.go
- dynamic_sharing_service/dynamic_policy_builder.go
- examples/profile/main.go
- examples/profile/profile.html
* `WithDocumentImages` and `WithDocumentDetails` to `DynamicPolicyBuilder`
> SDK-1417: Add DocumentDetails and DocumentImages to dynamic scenarios

- .travis.yml
- sonar-project.properties
* Sonarcloud static analysis to travis file
>  SDK-1391: Backport Sonarcloud.io changes to v2 release

- .travis.yml
* Sonarcloud static analysis to travis file
> SDK-1391: Move Static Code Analysis to Sonarcloud.io for v3

- consts/version.go
- sonar-project.properties
> 2.9.0 -> update version

- .gitignore
- .travis.yml
- examples/profile/dynamic-share.html
- examples/profile/error.html
- examples/profile/login.html
- examples/profile/profile.html
- sonar-project.properties
- Removed coveralls
- Sonar configuration
> NA: Sonar Cloud

- README.md
- _examples/aml/main.go
- aml/aml.go
- aml/service.go
- aml/service_test.go
- yoti_client.go
- Removed unnecessary `Aml` prefixes
> SDK-1661: Rename AML

- cryptoutil/crypto_utils.go
- cryptoutil/crypto_utils_test.go
- yoti_client_test.go
Following #148
-  Error message casing
> SDK-1661: Fix error message casing

- aml/service.go
Ported from https://github.com/getyoti/yoti-go-sdk/commit/819666f2886ba313d9122ebcff8491c6bf02edca#diff-f37f19aa58c436fad51e985daace6582 (unrelated to Doc Scan)
> NA: Declare variables in AML service

- yotierror/response.go
- yotierror/response_test.go
> SDK-1661: Fix error data object

- docscan/sandbox/client.go
- docscan/sandbox/client_test.go
- docscan/sandbox/request/check/document_authenticity_check_test.go
- docscan/sandbox/request/check/document_face_match_check_test.go
- docscan/sandbox/request/check/document_text_data_check_test.go
- docscan/sandbox/request/check/report/breakdown_test.go
- docscan/sandbox/request/check/report/recommendation_test.go
- docscan/sandbox/request/check/zoom_liveness_check_test.go
- docscan/sandbox/request/check_reports_test.go
- docscan/sandbox/request/filter/document_filter.go
- docscan/sandbox/request/filter/document_filter_test.go
- docscan/sandbox/request/response_config_test.go
- docscan/sandbox/request/task/document_text_data_extraction_task_test.go
- docscan/sandbox/request/task_results_test.go
Ported fixes from `SDK-1300-doc-scan-client` branch
- Implemented `DocumentFilterBuilder.WithDocumentTypes`
> SDK-1540: Sandbox Fixes

- _examples/docscansandbox/demo_test.go
- docscan/sandbox/request/check/document_text_data_check.go
- docscan/sandbox/request/check/document_text_data_check_test.go
- docscan/sandbox/request/task/document_text_data_extraction_task.go
- docscan/sandbox/request/task/document_text_data_extraction_task_test.go
- Support nested document fields
> SDK-1700: Support nested document fields

- dynamic/policy_builder.go
- dynamic/policy_builder_test.go
- dynamic/wanted_attribute_builder.go
- dynamic/wanted_attribute_test.go
- `"accept_self_asserted": false` is now included in the payload
> SDK-1618: Include accept_self_asserted false in JSON payload

- dynamic/policy_builder.go
Update policy builder docs after suggestion in https://github.com/getyoti/yoti-go-sdk/pull/171
> NA: document "options" on dynamic.policy_builder

- README.md
- URL was invalid for Go doc reference
> NA: Update Go dev docs reference

- _examples/docscan/models.sessionspec.go
- _examples/docscan/templates/success.html
- docscan/constants/constants.go
- docscan/sandbox/request/check/id_document_comparison_check.go
- docscan/sandbox/request/check/id_document_comparison_check_test.go
- docscan/sandbox/request/check_reports.go
- docscan/sandbox/request/check_reports_test.go
- docscan/sandbox/request/response_config_test.go
- docscan/session/create/check/document_comparison.go
- docscan/session/create/check/document_comparison_test.go
- docscan/session/retrieve/check_response.go
- docscan/session/retrieve/get_session_result.go
- docscan/session/retrieve/get_session_result_test.go
- ID Document Comparison check
- Checks not being displayed correctly in Doc Scan demo
> SDK-1720: Add ID Document Comparison check

- _examples/docscan/templates/success.html
- docscan/session/create/session_spec.go
- docscan/session/create/session_spec_test.go
- docscan/session/retrieve/get_session_result.go
- docscan/session/retrieve/get_session_result_test.go
- Ability to block the collection of biometric consent
> SDK-1740: Biometric Consent

- _examples/aml/go.sum
- _examples/docscan/go.sum
- _examples/docscansandbox/go.sum
- _examples/profile/go.sum
- _examples/profilesandbox/go.sum
- docscan/sandbox/request/task/document_text_data_extraction_task.go
- docscan/sandbox/request/task/document_text_data_extraction_task_test.go
- docscan/sandbox/request/task/text_data_extraction_reason.go
- docscan/sandbox/request/task/text_data_extraction_reason_test.go
- docscan/sandbox/request/task/text_data_extraction_recommendation.go
- docscan/sandbox/request/task/text_data_extraction_recommendation_test.go
- Added support to set in session feedback
> SDK-1789: In Session Feedback

- consts/version.go
- sonar-project.properties
Bumped minor version to `3.4.0`
> Merge master 3.3.0 → development

- _examples/docscan/handlers.session.go
- _examples/docscan/models.sessionspec.go
- _examples/docscan/routes.go
- _examples/docscan/templates/privacy.html
- docscan/session/create/sdk_config.go
- docscan/session/create/sdk_config_test.go
- Support for custom privacy policy URL
> SDK-1824: Privacy Policy URL

- .github/workflows/sonar.yaml
- .github/workflows/tests.yaml
- README.md
Adds github actions to this repository
> SDK-1854: Add github actions

- .github/workflows/sonar.yaml
- .github/workflows/tests.yaml
- README.md
Merge the github actions work back into Development.
> Rebase development onto master

- _examples/docscan/models.sessionspec.go
- _examples/docscan/templates/success.html
* RequestedThirdPartyCheck object to docscan session creation in example project
* Third Party Check breakdown to docscan/examples/templates/success.html
> SDK-1833: Add Third Party Check to DocScan Example Project

- .github/dependabot.yml
- Set @getyoti/yoti-sign to be reviewer and assignee for Dependabot
> NA: Set @getyoti/yoti-sign to be reviewer and assignee for Dependabot

- _examples/profile/profile.go
- _examples/profile/profile.html
- consts/attribute_names.go
- profile/user_profile.go
- profile/user_profile_test.go
- test/fixtures/RTWIdentityProfileReport.json
- Identity Profile Report attribute:
```go
var identityProfileReportValue map[string]interface{} = userProfile.IdentityProfileReport().Value() // JSON
```
> SDK-2083: Identity Profile Report attribute

- profile/attribute/attribute_details.go
- profile/attribute/date_attribute.go
- profile/attribute/document_details_attribute.go
- profile/attribute/generic_attribute.go
- profile/attribute/image_attribute.go
- profile/attribute/image_slice_attribute.go
- profile/attribute/json_attribute.go
- profile/attribute/multivalue_attribute.go
- profile/attribute/string_attribute.go
- profile/base_profile.go
- profile/user_profile.go
- profile/user_profile_test.go
- UserProfile
- GetAttributeByID
- GetSelfieAttributeByID
- GetDocumentImagesAttributeByID
See [examples](https://github.com/getyoti/yoti-go-sdk/blob/5acc3a53614648c24b498b506ec54b835cd5f10a/profile/user_profile_test.go#L40) for usage
> SDK-2094 Get Attribute by ID

- README.md
> Updated version to 3.9.0 in Readme

- docscan/session/create/filter/document_restrictions_filter.go
- docscan/session/create/filter/document_restrictions_filter_test.go
Added Support for expired documents at session creation using DOCUMENT_RESTRICTIONS
> SDK-2304:Added expired document feature to document restriction

- README.md
- consts/version.go
- requests/signed_message_test.go
- sonar-project.properties
Updated version info for release
> SDK-1193:updated version info

- digitalidentity/requests/signed_message_test.go
> SDK:2230-Expose-share-v2-api-version-update

- _examples/idv/models.sessionspec.go
- docscan/session/create/sdk_config.go
- docscan/session/create/sdk_config_test.go
```go
sdkConfig, err = create.NewSdkConfigBuilder().
WithAllowsCameraAndUpload().
WithPrimaryColour("#2d9fff").
WithSecondaryColour("#FFFFFF").
WithFontColour("#FFFFFF").
WithLocale("en-GB").
WithPresetIssuingCountry("GBR").
WithSuccessUrl("https://localhost:8080/success").
WithErrorUrl("https://localhost:8080/error").
WithPrivacyPolicyUrl("https://localhost:8080/privacy-policy").
WithIdDocumentTextExtractionGenericAttempts(2).
WithAllowHandOff(true).
WithBrandId("some_brand_id").
Build()
```
> Sdk 2469 go idv support brand id in session config

- _examples/idv/models.sessionspec.go
- docscan/constants/constants.go
- docscan/session/create/sdk_config.go
- docscan/session/create/sdk_config_test.go
```go
sdkConfig, err = create.NewSdkConfigBuilder().
WithAllowsCameraAndUpload().
WithPrimaryColour("#2d9fff").
WithSecondaryColour("#FFFFFF").
WithFontColour("#FFFFFF").
WithLocale("en-GB").
WithPresetIssuingCountry("GBR").
WithSuccessUrl("https://localhost:8080/success").
WithErrorUrl("https://localhost:8080/error").
WithPrivacyPolicyUrl("https://localhost:8080/privacy-policy").
WithIdDocumentTextExtractionGenericAttempts(2).
WithAllowHandOff(true).
WithEarlyBiometricConsentFlow().
Build()
```
> added configure-consent-screen-location and tests
