getyoti/yoti-go-sdk

- README.md
Go is the official name, it's just the website is called golang.org, because the domain go.com was taken by Disney at the time. You can see in the documentation they always refer to the language as Go - https://golang.org/project/. I changed the code markup to be Go instead of golang - although both would work, as golang is an alias of Go (https://github.com/github/linguist/blob/master/lib/linguist/languages.yml), I thought it would be more consistent to use Go.
> Updated README to change 'Golang' to 'Go'

- yoti_test.go
- yoticlient.go
- Added feature to take `formatted address` from `structured postal address` if `address` is missing
- Made a few changes based on `gometalinter`, there are lots more suggestions, I've added ticket SDK-449 to look at the rest of these
> SDK-342: Using formatted address for address

- CONTRIBUTING.md
- README.md
- anchor/anchorparser.go
- anchor/anchors.go
- anchor/signedtimestamp.go
- attribute/genericattribute.go
- attribute/image.go
- attribute/imageattribute.go
- attribute/imagesliceattribute.go
- attribute/item.go
- attribute/jsonattribute.go
- attribute/multivalueattribute.go
- attribute/parser.go
- attribute/stringattribute.go
- attribute/timeattribute.go
- examples/aml/main.go
- examples/go.mod
- examples/go.sum
- examples/profile/main.go
- go.mod
- go.sum
- yoti_test.go
- yoticlient.go
- yotiprofile.go
I've gone with the "Major branch" strategy outlined in the [Go wiki on Modules ](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher). This allows us to carry on working on master, and if we do need to change anything for version 2 (after we've released version 3), then we can make a branch for v2, and make any bug fixes there. 
I'll add further detail to a wiki shortly, including what we'll need to do with each minor and major release going forwards.
When we release the major version, it will just be a case of renaming the module, and changing the v2s to v3s (or using [this handy tool](https://github.com/marwan-at-work/mod)). 
Also updated some fields to make them read only. 
This will require an update to the developer docs.
> [SDK-609]: Create Yoti v2 module

- README.md
- attribute/parser.go
- crypto.go
- examples/profile/main.go
- go.mod
- go.sum
- yoti_test.go
- Add INT content type, currently only accessible through `profile.GetAttribute(attributeName)`
- Since I wanted to make use of the `"gotest.tools/assert"` package to test this, I thought I might as well implement the rest of the tests to use this
- Referencing this package adds `+incompatible` to it in the `go.mod` file. This just means that the referenced package is on a major version > 1, and hasn't opted to use modules (yet). See here for more information on this - https://github.com/golang/go/wiki/Modules#can-a-module-consume-a-v2-package-that-has-not-opted-into-modules-what-does-incompatible-mean
> SDK-867 SDK-865: INT Content Type, assertions in tests

- .travis.yml
- CONTRIBUTING.md
- attribute/parser.go
- endpoint.go
- sonar-project.properties
- yoticlient.go
After refactoring I got this error on the Travis builds:
```bash
./yoticlient.go:92:32: too many arguments in call to getProfileEndpoint
have (string, string, string, string)
want (string, string, string)
```
It looked like there was a clash between the previous version of the `getProfileEndpoint` method, and the current version. 
I ran the Travis docker image locally and looked at this build - 
I could see the updated version of the sdk in `~/getyoti/yoti-go-sdk`, but when I was in `~/gopath/src/github.com/getyoti/yoti-go-sdk`, that's where I could see the old one.
It looks like the old version is being cached in here, so I had to remove the caching. I wouldn't have thought that Go would prioritise looking in the gopath first, when GO111MODULE=on, for versions > 1.10.x, but it looks like …
> SDK-895: Undefined content types

- conversion.go
- crypto.go
- endpoint.go
- httpclient.go
- httprequester.go
- requests/signed_message.go
- yoti_test.go
- yoticlient.go
* SDK-723
* SDK-1119
* Added SignedMessage builder for signed requests (using Golang http request type)
* Update Client.makeRequest to use SignedMesssage builder to create the headers and twiddle the endpoint to include timestamp and nonce magically
* Remove timestamp/nonce from endpoints.go 's responsibilities.
* Remove digest generation from yoticlient.go's responsibilities.
* Client's makeRequest receiver now takes http.Request as parameter (i.e. a SignedMessage), instead of attempting to build its own http Request object from parameters.
* Client embeds a http.Client to allow mocking of http transport/response by unit tests.
---
```
pemBytes, err := ioutil.ReadFile(pemFile)
request, err := requests.SignedRequest{
HTTPMethod: http.MethodPost,
BaseURL: docScanURL,
Endpoint: "/sessions", …
```
> SDK-1077: signed request builder

- requests/signed_message_test.go
- validate.go
- wantedattribute_test.go
- wantedattributebuilder.go
* Add `validate.go` with `notEmpty` to verify a string is not empty
* `WantedAttribute.MarshalJSON` returns an error message if `attr.name` is empty
> SDK-1283: Prevent Empty Wanted Attribute Names

- .travis.yml
- age_verifications.go
- Adding `goimports` check to Travis, so we fail earlier (rather than on pipeline)
- This modifies the `go.mod` and `go.sum` files (which are checked in Travis), so we're having to add `go mod tidy` to the go generate command before comparing, but...
- `go mod` isn't available in older versions, so we have to add an additional conditional compilation to avoid this in earlier versions
> SDK-1305: Add goimports check to Travis, run goimports

- sandbox/client.go
- yoti_test.go
- yoticlient.go
* `http.Client` instantiations in `yoticlient.go` and `sandbox/client.go` set Timeout attribute
> SDK-1104: Requests to our API shold time out if unavailable

- attribute/attribute_details.go
- attribute/documentdetailsattribute.go
- attribute/genericattribute.go
- attribute/imageattribute.go
- attribute/imagesliceattribute.go
- attribute/jsonattribute.go
- attribute/multivalueattribute.go
- attribute/stringattribute.go
- attribute/timeattribute.go
- yoti_test.go
Add Name() and ContentType() methods to expose functionality previously
accessed through the yotiprotoattr.Attribute interface
> SDK-1252: Make embedded yotiprotoattr attribute a private member

- attribute/imagesliceattribute.go
- attribute/parser.go
- yoti_test.go
* `attribute.parseValue` parsed image types to `*attribute.Image`
* `ContentType_UNDEFINED` explicitly parses attribute data to a string, without emitting warning logging
> SDK-849: Change how generic attribute parsing is handled in Go

- crypto.go
- errors.go
- examples/aml/main.go
- examples/profile/main.go
- yoti_test.go
- yoticlient.go
Change type of Key in Client. Add LoadPEM method for loading Key from
PEM bytes
> SDK-1292: Load PEM file as part of client initialisation

- activitydetails.go
- attribute/timeattribute_test.go
- yoti_test.go
- yoticlient.go
* `ActivityDetails.Timestamp()` returns `time.Time`
* `TestYotiClient_ParseWithoutProfile_Success` uses a real RFC3339 timestamp, instead of a dummy value (123456789)
> SDK-903: Update timestamp for ActivityDetails to time.Time object

- attribute/issuance_details.go
- extension/third_party_attribute_extension.go
- yoti_client.go
In some places, a manually entered format string that did not support
timezones was being used, in others time.RFC3339 (which does not support
microseconds) was being used instead of time.RFC3339Nano (which does support
microseconds).
Fix all of these to use time.RFC3339Nano
> SDK-1367: Fix incorrect format being used to parse RFC3339

- attribute/date_attribute.go
- attribute/date_attribute_test.go
- yoti_profile.go
* Dependency on araddon/dateparser
* TimeAttribute to support flexible parsing, allowing it to parse datetimes as well as dates.
I'm not sure whether this is an approach we want to take with time attribute, as it doesn't contain information on what was parsed - since it leaves 'unused' attributes as the 0-value (or 1 for day) there's no way to tell the difference between 1st Jan and No Data.
> SDK-1347 timeattribute flexible parsing

- attribute/json_attribute.go
- yoti_client_test.go
* `JSONAttribute.Value()` to return `map[string]interface{}`
> SDK-665: Change StructuredPostalAddress interface to map

- README.md
- anchor/anchor_parser.go
- anchor/anchor_parser_test.go
- anchor/anchors.go
- attribute/image_slice_attribute_test.go
- attribute/string_attribute_test.go
We'll need to update the dev docs after this change too.
> SDK-1027: Change anchor value to be a single string

- sandbox/client.go
- sandbox/client_test.go
- sandbox/profile.go
- sandbox/profile_test.go
* `LoadPEMFile` helper added to `sandbox.Client` to read Sandbox App private key
* Workaround function `WithoutAttributes` no longer sets a dummy attribute as sandbox now supports a share with no attributes and no longer supports dummy attributes being set.
* `Profile::WithoutAttributes`
> SDK-1438: Add Load PEM helper to sandbox client

- profile/sandbox/client.go
- profile/sandbox/client_test.go
- yoticlient.go
- yoticlient_test.go
Branched off https://github.com/getyoti/yoti-go-sdk/pull/116, see changes for this branch here:
https://github.com/getyoti/yoti-go-sdk/compare/SDK-1527-SandboxDocumentation...SDK-1500-UseEnvApiURLForYotiClient
We are already using this .env variable for Sandbox, this is just to update the YotiClient to do the same too. 
I opted to keep the `.OverrideAPIURL` in the sandbox example files (when we could instead just use the .env files), as I think it makes it clearer to the client that the client is not pointing at the same place
> SDK-1500: Use .env `YOTI_API_URL` for calls through YotiClient

- README.md
- instead of Yoti.Client{}
This is so the .PEM file will be validated before any calls are made
> SDK-1490: Update README to use "NewClient" initialiser

- attribute/json_attribute.go
- Use `decoder.UseNumber()` option in decoder for JSON values is so int values are parsed as `json.number` rather than float64
- Integration tests updated in a separate PR
- See https://eager.io/blog/go-and-json/ for more information:
> your numbers will always be of typefloat64, and will need to be casted to int, for example. If you have a particular need to get ints directly, you can use the UseNumber method. Which gives you an object which can be converted to either a float64 or an int at your discretion.
> SDK-1491: Use json.number decoder for JSON values

- aml/service.go
- aml/service_test.go
- dynamic/service_test.go
- dynamic/share_url.go
- profile/service.go
- profile/service_test.go
- requests/client.go
- requests/request.go
- yoti_client_test.go
Following #137 
- Response body is now only appended when available (no trailing `:`)
- Reset the response body after reading so that the response can be used by callers
- `defaultUnknownErrorMessageConst` is now the message string, rather than a format - status code is now always prefixed, e.g. `404: Profile not found`
> SDK-1659: Response Errors

- requests/signed_message.go
This would explain why our metrics are a bit off for Go versions...
> NA: Correct "X-Yoti-SDK-Version" request header

- _examples/aml/main.go
- dynamic/policy_builder.go
- dynamic/scenario_builder_test.go
- profile/application_profile.go
- profile/attribute/anchor/anchor_parser_test.go
- profile/attribute/definition_test.go
- profile/attribute/document_details_attribute_test.go
- profile/attribute/parser.go
- profile/base_profile.go
- profile/sandbox/anchor.go
- profile/sandbox/attribute.go
- profile/sandbox/document_images.go
- profile/service.go
- profile/service_test.go
- profile/user_profile.go
- profile/user_profile_test.go
- requests/signed_message.go
- util/conversion.go
- Correct godoc string prefixes (or make unexported if not necessary)
- Rename variable names so they don't shadow other names, or packages
- Remove unused functions/variables, change empty slice initialisation (https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices)
> SDK-1661: Tidying up before major release

- .travis.yml
- README.md
- aml/service_test.go
- cryptoutil/crypto_utils_test.go
- dynamic/policy_builder_test.go
- file/file_test.go
- profile/attribute/age_verifications.go
- profile/attribute/age_verifications_test.go
- profile/receipt_parser.go
- profile/sandbox/tokenrequest_test.go
- profile/user_profile.go
- requests/request_test.go
- yoti_client_test.go
- yotierror/response_test.go
- Additional test coverage
- SonarCloud badges to README
- `AgeVerification{}.New()` changed to `NewAgeVerification()`
- Reusing `parseEncryptedProto()` for application profile
- Go master from Travis (we already allowed failures for this and it was taking 4 times longer than stable releases)
> SDK-1690: Test Coverage

- docscan/client.go
- docscan/constants/constants.go
- docscan/session/create/check/constants.go
- docscan/session/create/check/liveness.go
- docscan/session/create/task/text_extraction_test.go
- docscan/session/retrieve/check_response.go
- docscan/session/retrieve/generated_check_response.go
- docscan/session/retrieve/get_session_result.go
- docscan/session/retrieve/get_session_result_test.go
- docscan/session/retrieve/id_document_resource_response.go
- docscan/session/retrieve/resource_container.go
- docscan/session/retrieve/task_response.go
- docscan/session/retrieve/task_response_test.go
- docscan/session/retrieve/text_extraction_task_response.go
This is a proposed solution for dealing with the handling of various subtypes when parsing the GetSession response.
CheckResponses can be (based on the value of the `type` field):
- CheckResponse
- AuthenticityCheckResponse
- FaceMatchCheckResponse
- LivenessCheckResponse
- TextDataCheckResponse
- may be others in future
Likewise, a GeneratedChecks can be:
- GeneratedCheck 
- GeneratedTextDataCheckResponse
- may be others in future
So we want to add convenience methods to _filter_:
- `GetSessionResult.Checks` to return the the above subsets listed, and
- `TaskResponse.GeneratedChecks` to only return the `GeneratedTextDataCheckResponses`
There are two other "subtypes" which will need filtering too, but thought I'd check this was the right approach before applying to those as well.
At first …
> SDK-1300: Add json subtype parsing with custom JSON unmarshalling

- aml/aml.go
- cryptoutil/crypto_utils_test.go
- extension/third_party_attribute_extension_test.go
- profile/attribute/anchor/anchor_parser.go
- profile/attribute/anchor/anchor_parser_test.go
- profile/attribute/date_attribute.go
- profile/attribute/generic_attribute.go
- profile/attribute/issuance_details.go
- profile/attribute/parser.go
- profile/user_profile_test.go
Integrators could be using std err and std out for their own logging. Enough information should be able to be gleamed from the error and the stack trace
> SDK-1723: Remove logging from SDK

- extension/location_constraint_extension.go
- extension/location_constraint_extension_test.go
- extension/third_party_attribute_extension.go
- extension/third_party_attribute_extension_test.go
- `LocationConstraintExtensionBuilder.WithUncertainty()` renamed to `LocationConstraintExtensionBuilder.WithMaxUncertainty()`
- `ThirdPartyAttributeExtensionBuilder.Build()` now returns an error
> SDK-1618: Dynamic Scenario Extensions

- dynamic/policy_builder_test.go
- dynamic/scenario_builder_test.go
- dynamic/wanted_attribute_builder.go
- dynamic/wanted_attribute_test.go
Amendment to #174 
- `accept_self_asserted` wanted attribute property will now default to `false`, instead of being omitted from payload.
> SDK-1618: Default accept_self_asserted to false

- dynamic/policy_builder.go
- dynamic/policy_builder_test.go
- dynamic/wanted_attribute_builder.go
- dynamic/wanted_attribute_test.go
Amendment to #174 - reinstates custom `MarshalJSON()`
- Keeps wanted attribute fields private inline with other dynamic scenario request structs
> SDK-1618: Wanted Attribute

- profile/attribute/anchor/anchor_parser.go
- profile/attribute/anchor/anchor_parser_test.go
As this was setting signedTimestamp to nil, and then taking the value of it, it will have thrown a nil pointer exception
> SDK-1726: Fix anchor parsing when signedTimestamp bytes are invalid

- _examples/profile/main.go
- _examples/profile/profile.html
This fix is just to not assume full name is present in the template, and wrap it in an IF statement.
This issue was being hidden by another issue - we were panicking instead of gracefully handling the error. This meant the request was retried with the same token, which had then expired as it had been used once. 
I have updated the panic instances to redirect to the error page with the error information, (where we're not already trying to parse the error page)
> SDK-1729: Fix profile example

- docscan/client.go
- docscan/client_test.go
- docscan/session/create/check/face_match_test.go
- docscan/session/create/filter/document_restriction_test.go
- docscan/session/create/filter/document_restrictions_filter_test.go
- docscan/session/create/sdk_config_test.go
- docscan/session/create/session_spec_test.go
- docscan/session/create/task/text_extraction_test.go
- docscan/session/retrieve/get_session_result_test.go
- docscan/session/retrieve/id_document_resource_response_test.go
- docscan/session/retrieve/resource_container_test.go
- docscan/session/retrieve/task_response_test.go
- Added Doc Scan test coverage
- `client.GetMediaContent()` content type validation - now returns error when content type is not available.
> SDK-1300: Add Doc Scan test coverage

- docscan/session/create/check/document_authenticity.go
- docscan/session/create/check/document_authenticity_test.go
- Ability to configure manual fallback value on Document Authenticity Check
> SDK-1733: Add manual fallback option to Doc Auth check

- docscan/sandbox/request/task/document_text_data_extraction_task.go
- docscan/sandbox/request/task/document_text_data_extraction_task_test.go
- Sandbox support for setting document ID photo
Note: SDK already allows chip data to be ignored/desired and parses ID photo in response
> SDK-1640: Chip Data

- _examples/docscan/handlers.session.go
- _examples/docscan/models.sessionspec.go
- docscan/client.go
- docscan/client_test.go
- `func (c *Client) GetMediaContent()` will now return `nil` media for `204` responses
> SDK-1808: Handle media 204 no content response

- _examples/docscan/templates/success.html
* Demo Docscan project template showing authenticity check instead of liveness check result
> NA: Fix authenticty checks being shown under liveness checks

- _examples/docscan/handlers.session.go
- Return error page when it is set in example project - we were carrying on down the codepath with an invalid state
- Update status codes to better reflect what has occurred
> SDK-1976: Catch panic with invalid settings

- .pre-commit-config.yaml
- _examples/aml/go.mod
- _examples/aml/go.sum
- _examples/docscansandbox/go.sum
- _examples/idv/go.mod
- _examples/idv/go.sum
- _examples/idv/models.sessionspec.go
- _examples/idv/templates/success.html
- _examples/profile/go.mod
- _examples/profile/go.sum
- _examples/profilesandbox/go.mod
- _examples/profilesandbox/go.sum
- docscan/session/create/check/third_party_identity_test.go
- docscan/session/create/check/watchlist_advanced_ca.go
- docscan/session/create/check/watchlist_advanced_ca_custom.go
- docscan/session/create/check/watchlist_advanced_ca_custom_test.go
- docscan/session/create/check/watchlist_advanced_ca_matching_strategy.go
- docscan/session/create/check/watchlist_advanced_ca_sources.go
- docscan/session/create/check/watchlist_advanced_ca_yoti.go
- docscan/session/create/check/watchlist_advanced_ca_yoti_test.go
- docscan/session/retrieve/ca_sources.go
- docscan/session/retrieve/check_response.go
- docscan/session/retrieve/get_session_result.go
- docscan/session/retrieve/get_session_result_test.go
- docscan/session/retrieve/search_config.go
- requests/signed_message_test.go
- test/fixtures/watchlist_advanced_ca_profile_custom.json
- Advanced CA Check
```go
advancedCAYotiAccountCheck, err := check.NewRequestedWatchlistAdvancedCACheckYotiAccountBuilder().
WithRemoveDeceased(true).
WithShareURL(true).
WithSources(check.RequestedTypeListSources{
Types: []string{"pep", "fitness-probity", "warning"}}).
WithMatchingStrategy(check.RequestedFuzzyMatchingStrategy{Fuzziness: 0.5}).
Build()
```
OR
```go
advancedCACustomAccountCheck, err := check.NewRequestedWatchlistAdvancedCACheckCustomAccountBuilder().
WithAPIKey("api-key").
WithMonitoring(true).
WithTags(map[string]string{
"tag_name": "value",
}).
WithClientRef("client-ref").
WithMatchingStrategy(check.RequestedExactMatchingStrategy{ExactMatch: true}).
Build()
```
```go
getSessionResult.WatchlistAdvancedCAChecks()
```
Demo Project screenshot:
> SDK-1909: Add Advanced CA Check

- _examples/idv/main.go
- _examples/idv/templates/success.html
- docscan/session/retrieve/failure_reason_response.go
- docscan/session/retrieve/get_session_result.go
- docscan/session/retrieve/get_session_result_test.go
- docscan/session/retrieve/identity_profile_response.go
- test/fixtures/GetSessionResultWithIdentityProfile.json
**Added**
- IdentityProfile to IDV GetSessionResult:
```go
getSessionResult, err := client.GetSession(sessionId)
if err != nil {
return err
}
identityProfile := getSessionResult.IdentityProfileResponse
subjectId := identityProfile.SubjectId
result := identityProfile.Result
failureReasonCode := identityProfile.FailureReasonResponse.ReasonCode
```
example IdentityProfile.Report value:
```json
"trust_framework": "UK_TFIDA",
"schemes_compliance": [{
"scheme": {
"type": "DBS",
"objective": "STANDARD"
},
"requirements_met": true,
"requirements_not_met_info": "info here"
}
],
"media": {
"id": "c69ff2db-6caf-4e74-8386-037711bbc8d7",
"type": "IMAGE",
"created": "2022-03-29T11:39:24Z",
"last_updated": "2022-03-29T11:39:24Z"
}
```
MediaID can be retrieved with:
```go
media := …
```
> Retrieve the identity profile in the IDV response

- _examples/idv/models.sessionspec.go
- docscan/session/create/session_spec.go
- docscan/session/create/session_spec_test.go
**Added**
-  Subject to IDV request
requested with:
```go
subject := []byte(`{
"subject_id": "subject ID"
}`)
sessionSpecification, err := NewSessionSpecificationBuilder().
WithSubject(subject).
Build()
```
example of Session Result containing the subject_id specified when the session was crated:
```json
{
"session_id": "a1746488-efcc-4c59-bd28-f849dcb933a2",
"client_session_token_ttl": 599,
"user_tracking_id": "user-tracking-id",
"biometric_consent": "2022-03-29T11:39:08.473Z",
"state": "COMPLETED",
"client_session_token": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"identity_profile": {
"subject_id": "subject ID",
"result": "DONE",
"failure_reason": {
"reason_code": "MANDATORY_DOCUMENT_COULD_NOT_BE_PROVIDED"
},
"identity_profile_report": {
"trust_framework": "UK_TFIDA", …
```
> Add subject to IDV request

- docscan/session/create/constants.go
- docscan/session/create/sdk_config.go
- docscan/session/create/sdk_config_test.go
**Added**
WithIdDocumentTextExtractionCategoryRetries, WithIdDocumentTextExtractionReclassificationRetries, WithIdDocumentTextExtractiongenericRetries to the SdkConfig
```go
sdkConfig, err := NewSdkConfigBuilder().
WithIdDocumentTextExtractionGenericRetries(3).
WithIdDocumentTextExtractionCategoryRetries("CATEGORY", 2).
WithIdDocumentTextExtractionReclassificationRetries(2).
Build()
```
> Add Attempts Configuration to IDV with Relevant Tests

- _examples/idv/models.sessionspec.go
- _examples/idv/templates/success.html
- docscan/session/create/session_spec.go
- docscan/session/create/session_spec_test.go
- docscan/session/retrieve/get_session_result.go
- docscan/session/retrieve/get_session_result_test.go
- docscan/session/retrieve/identity_profile_preview.go
- test/fixtures/GetSessionResultWithIdentityProfile.json
**Added**
- IdentityProfilePreview to Session Specification Builder
**Requested with**
```go	
sessionSpec, err = create.NewSessionSpecificationBuilder().
WithClientSessionTokenTTL(6000).
WithResourcesTTL(900000).
WithUserTrackingID("some-tracking-id").
WithSDKConfig(sdkConfig).
WithIdentityProfileRequirements(identityProfile).
WithCreateIdentityProfilePreview(true).
WithSubject(subject).
Build()
```
- IdentityProfilePreview to IDV GetSessionResult:
```go
getSessionResult, err := client.GetSession(sessionId)
if err != nil {
return err
}
identityProfilePreview := getSessionResult.IdentityProfilePreview
```
Example available when running the idv example project at https://localhost:8080/dbs
> Identity profile preview

- _examples/idv/models.sessionspec.go
- docscan/session/create/sdk_config.go
- docscan/session/create/sdk_config_test.go
**Added**
WithIdDocumentTextExtractionCategoryAttempts, WithIdDocumentTextExtractionReclassificationAttempts, WithIdDocumentTextExtractiongenericAttempts to the SdkConfig
```go
sdkConfig, err := NewSdkConfigBuilder().
WithIdDocumentTextExtractionGenericAttempts(3).
WithIdDocumentTextExtractionCategoryAttempts("CATEGORY", 2).
WithIdDocumentTextExtractionReclassificationAttempts(2).
Build()
```
> Renamed Retries to Attempts

- _examples/idv/models.sessionspec.go
- docscan/client.go
- docscan/client_test.go
- docscan/session/create/filter/orthogonal_restrictions_filter.go
- docscan/session/create/filter/orthogonal_restrictions_filter_test.go
- docscan/supported/supported_documents.go
**Added**
- Support for non latin documents when fetching supported documents
**Requested with**
```go	
result, err := client.GetSupportedDocuments(true)
```
> Sdk 2039 go support for non latin documents when fetching supported documents

- _examples/idv/models.sessionspec.go
- _examples/idv/templates/success.html
- docscan/session/create/import_token.go
- docscan/session/create/import_token_test.go
- docscan/session/create/session_spec.go
- docscan/session/retrieve/get_session_result.go
- docscan/session/retrieve/import_token.go
**Added**
- ImportToken to Session Specification Builder and a ImportTokenBuilder
**Requested with**
```go	
ttl := time.Hour * 24 * 30
importToken, err := create.NewImportTokenBuilder().
WithTTL(int(ttl.Seconds())).
Build()
if err != nil {
return nil, err
}
sessionSpec, err = create.NewSessionSpecificationBuilder().
WithClientSessionTokenTTL(6000).
WithResourcesTTL(900000).
WithUserTrackingID("some-tracking-id").
WithSDKConfig(sdkConfig).
WithIdentityProfileRequirements(identityProfile).
WithCreateIdentityProfilePreview(true).
WithSubject(subject).
WithImportToken(importToken).
Build()
```
- ImportTokenResponse to IDV GetSessionResult:
```go
getSessionResult, err := client.GetSession(sessionId)
if err != nil {
return err
}
importTokenResponse := getSessionResult.ImportTokenResponse
``` …
> Added support for ImportToken

- _examples/digitalidentity/error_receipt.html
- _examples/digitalidentity/receipt.go
- _examples/digitalidentity/requirements_not_met_detail.html
- digitalidentity/receipt.go
- digitalidentity/service.go
- digitalidentity/service_test.go
- digitalidentity/share_receipt.go
Expanded SharedReceiptResponse to include details about the error:
**Before:**
```go
type SharedReceiptResponse struct {
ID                 string
SessionID          string
RememberMeID       string
ParentRememberMeID string
Timestamp          string
Error              string
UserContent        UserContent
ApplicationContent ApplicationContent
}
```
**After:**
```go
type SharedReceiptResponse struct {
ID                 string
SessionID          string
RememberMeID       string
ParentRememberMeID string
Timestamp          string
Error              string
ErrorReason        ErrorReason
UserContent        UserContent
ApplicationContent ApplicationContent
}
type ErrorReason struct {
RequirementsNotMetDetails []RequirementsNotMetDetail `json:"requirements_not_met_details"`
}
type …
```
> SDK-2356: Added ErrorReason to SharedReceiptResponse
